Script started on Thu 13 Oct 2016 02:18:22 PM MDT
]0;joey@joey-P7xxDM-G: ~/113cse/lab5[01;32mjoey@joey-P7xxDM-G[00m:[01;34m~/113cse/lab5[00m$ gs[Kcc=[K -g -Wall -c lab[K[K[Kzombie.c
]0;joey@joey-P7xxDM-G: ~/113cse/lab5[01;32mjoey@joey-P7xxDM-G[00m:[01;34m~/113cse/lab5[00m$ gcc -g -Wall lab5.c zombie.o
]0;joey@joey-P7xxDM-G: ~/113cse/lab5[01;32mjoey@joey-P7xxDM-G[00m:[01;34m~/113cse/lab5[00m$ ./a.out
What to do? 
n, enter new zombie
p, print zombie info
f, fight the zombie behind you. (exit)
n
Is the zombie dead? Y/N
1 y
How many toes did this mutant zombie have?
1
what day was this zombie found?
enter:
1 for monday
2 for tuesday
3 for wednesday
4 for thrusday
5 for friday
6 for saturday
7 for sunday.
2
enter the time HH:MM:SS
13:24:12
index = 0
What to do? 
n, enter new zombie
p, print zombie info
f, fight the zombie behind you. (exit)
n
Is the zombie dead? Y/N
y
How many toes did this mutant zombie have?
3
what day was this zombie found?
enter:
1 for monday
2 for tuesday
3 for wednesday
4 for thrusday
5 for friday
6 for saturday
7 for sunday.
8 5
enter the time HH:MM:SS
12:45:12
index = 1
What to do? 
n, enter new zombie
p, print zombie info
f, fight the zombie behind you. (exit)
n
Is the zombie dead? Y/N
n
Assuming you killed it, how much blood did it have? (mL or L please)
13.23423
what day was this zombie found?
enter:
1 for monday
2 for tuesday
3 for wednesday
4 for thrusday
5 for friday
6 for saturday
7 for sunday.
7
enter the time HH:MM:SS
15:22:30
index = 2
What to do? 
n, enter new zombie
p, print zombie info
f, fight the zombie behind you. (exit)
n
Is the zombie dead? Y/N
y
How many toes did this mutant zombie have?
8
what day was this zombie found?
enter:
1 for monday
2 for tuesday
3 for wednesday
4 for thrusday
5 for friday
6 for saturday
7 for sunday.
3
enter the time HH:MM:SS
08:03:19
index = 3
What to do? 
n, enter new zombie
p, print zombie info
f, fight the zombie behind you. (exit)
n
Is the zombie dead? Y/N
n
Assuming you killed it, how much blood did it have? (mL or L please)
34.245
what day was this zombie found?
enter:
1 for monday
2 for tuesday
3 for wednesday
4 for thrusday
5 for friday
6 for saturday
7 for sunday.
2 1
enter the time HH:MM:SS
00:00:12
index = 4
What to do? 
n, enter new zombie
p, print zombie info
f, fight the zombie behind you. (exit)
p
zombie 0
The zombie was found dead.
the zombie had 1 toes.
the zombie was found on Tuesday
the zombie was found at 13:24:12.
zombie 1
The zombie was found dead.
the zombie had 3 toes.
the zombie was found on Friday
the zombie was found at 12:45:12.
zombie 2
the zombie was found ALIVE.
13.234230 mL of blood was drained from the corpse.
the zombie was found on Sunday
the zombie was found at 15:22:30.
zombie 3
The zombie was found dead.
the zombie had 8 toes.
the zombie was found on Wednesday
the zombie was found at 8:3:19.
zombie 4
the zombie was found ALIVE.
34.244999 mL of blood was drained from the corpse.
the zombie was found on Monday
the zombie was found at 0:0:12.
What to do? 
n, enter new zombie
p, print zombie info
f, fight the zombie behind you. (exit)
n
Is the zombie dead? Y/N
n
Assuming you killed it, how much blood did it have? (mL or L please)
2312.3
what day was this zombie found?
enter:
1 for monday
2 for tuesday
3 for wednesday
4 for thrusday
5 for friday
6 for saturday
7 for sunday.
2
enter the time HH:MM:SS
23  13:13:13
index = 5
What to do? 
n, enter new zombie
p, print zombie info
f, fight the zombie behind you. (exit)
p
zombie 0
The zombie was found dead.
the zombie had 1 toes.
the zombie was found on Tuesday
the zombie was found at 13:24:12.
zombie 1
The zombie was found dead.
the zombie had 3 toes.
the zombie was found on Friday
the zombie was found at 12:45:12.
zombie 2
the zombie was found ALIVE.
13.234230 mL of blood was drained from the corpse.
the zombie was found on Sunday
the zombie was found at 15:22:30.
zombie 3
The zombie was found dead.
the zombie had 8 toes.
the zombie was found on Wednesday
the zombie was found at 8:3:19.
zombie 4
the zombie was found ALIVE.
34.244999 mL of blood was drained from the corpse.
the zombie was found on Monday
the zombie was found at 0:0:12.
What to do? 
n, enter new zombie
p, print zombie info
f, fight the zombie behind you. (exit)
f
You walk outside, you risk your life. You take a drink of water, you risk your life. Nowadays you breath and you risk your life. You don't have a choice. The only thing you can choose is what you're risking it for.
stay alert and watch for zombies. 
goodluck out there. goodbye.
]0;joey@joey-P7xxDM-G: ~/113cse/lab5[01;32mjoey@joey-P7xxDM-G[00m:[01;34m~/113cse/lab5[00m$ exit
exit

Script done on Thu 13 Oct 2016 02:21:13 PM MDT
