Script started on Thu 13 Oct 2016 02:21:56 PM MDT
]0;joey@joey-P7xxDM-G: ~/113cse/lab5[01;32mjoey@joey-P7xxDM-G[00m:[01;34m~/113cse/lab5[00m$ gcc -g -Wall smallest.c
]0;joey@joey-P7xxDM-G: ~/113cse/lab5[01;32mjoey@joey-P7xxDM-G[00m:[01;34m~/113cse/lab5[00m$ ./.aout[K[K[K[K[Ka.out
232792560
]0;joey@joey-P7xxDM-G: ~/113cse/lab5[01;32mjoey@joey-P7xxDM-G[00m:[01;34m~/113cse/lab5[00m$ exit
exit

Script done on Thu 13 Oct 2016 02:22:10 PM MDT
