Script started on Thu 13 Oct 2016 02:22:50 PM MDT
]0;joey@joey-P7xxDM-G: ~/113cse/lab5[01;32mjoey@joey-P7xxDM-G[00m:[01;34m~/113cse/lab5[00m$ gcc -g -Wall sunday.c
]0;joey@joey-P7xxDM-G: ~/113cse/lab5[01;32mjoey@joey-P7xxDM-G[00m:[01;34m~/113cse/lab5[00m$ ./a.out
 the number of months that start on a sunday since long ago in 1901 is 171
]0;joey@joey-P7xxDM-G: ~/113cse/lab5[01;32mjoey@joey-P7xxDM-G[00m:[01;34m~/113cse/lab5[00m$ x[Kexit
exit

Script done on Thu 13 Oct 2016 02:23:02 PM MDT
