Script started on Fri 21 Oct 2016 10:44:08 AM MDT
]0;joey@joey-P7xxDM-G: ~/113cse/lab6[01;32mjoey@joey-P7xxDM-G[00m:[01;34m~/113cse/lab6[00m$ gcc -g -Wall bad.c
]0;joey@joey-P7xxDM-G: ~/113cse/lab6[01;32mjoey@joey-P7xxDM-G[00m:[01;34m~/113cse/lab6[00m$ ./a.out
Khoor/#zruog1
Khoor/#zruog1
]0;joey@joey-P7xxDM-G: ~/113cse/lab6[01;32mjoey@joey-P7xxDM-G[00m:[01;34m~/113cse/lab6[00m$ exit
exit

Script done on Fri 21 Oct 2016 10:44:20 AM MDT
