Script started on Fri 21 Oct 2016 10:50:16 AM MDT
]0;joey@joey-P7xxDM-G: ~/113cse/lab6[01;32mjoey@joey-P7xxDM-G[00m:[01;34m~/113cse/lab6[00m$ gcc i[K-g -Wall insert_sort.c
]0;joey@joey-P7xxDM-G: ~/113cse/lab6[01;32mjoey@joey-P7xxDM-G[00m:[01;34m~/113cse/lab6[00m$ ./a.out 15 [K[K2 5 9 32 25 8 19 200 10
5
8
9
10
12
19
25
32
200
]0;joey@joey-P7xxDM-G: ~/113cse/lab6[01;32mjoey@joey-P7xxDM-G[00m:[01;34m~/113cse/lab6[00m$ exit
exit

Script done on Fri 21 Oct 2016 10:50:41 AM MDT
