Script started on Fri 21 Oct 2016 10:44:33 AM MDT
]0;joey@joey-P7xxDM-G: ~/113cse/lab6[01;32mjoey@joey-P7xxDM-G[00m:[01;34m~/113cse/lab6[00m$ .[Kgcc -g -Wall product.c
]0;joey@joey-P7xxDM-G: ~/113cse/lab6[01;32mjoey@joey-P7xxDM-G[00m:[01;34m~/113cse/lab6[00m$ ./a.out
product is 151200
]0;joey@joey-P7xxDM-G: ~/113cse/lab6[01;32mjoey@joey-P7xxDM-G[00m:[01;34m~/113cse/lab6[00m$ exit
exit

Script done on Fri 21 Oct 2016 10:44:46 AM MDT
