Script started on Fri 21 Oct 2016 10:48:14 AM MDT
]0;joey@joey-P7xxDM-G: ~/113cse/lab6[01;32mjoey@joey-P7xxDM-G[00m:[01;34m~/113cse/lab6[00m$ gcc -g -Wall scor[K[K[Kort_easy.c
]0;joey@joey-P7xxDM-G: ~/113cse/lab6[01;32mjoey@joey-P7xxDM-G[00m:[01;34m~/113cse/lab6[00m$ ./a.out
2	5	8	20
]0;joey@joey-P7xxDM-G: ~/113cse/lab6[01;32mjoey@joey-P7xxDM-G[00m:[01;34m~/113cse/lab6[00m$ ./a.outgcc -g -Wall sort_easy.c
]0;joey@joey-P7xxDM-G: ~/113cse/lab6[01;32mjoey@joey-P7xxDM-G[00m:[01;34m~/113cse/lab6[00m$ gcc -g -Wall sort_easy.c./a.out[K
4	5	6	7	8	9	10
]0;joey@joey-P7xxDM-G: ~/113cse/lab6[01;32mjoey@joey-P7xxDM-G[00m:[01;34m~/113cse/lab6[00m$ ./a.outgcc -g -Wall sort_easy.c
]0;joey@joey-P7xxDM-G: ~/113cse/lab6[01;32mjoey@joey-P7xxDM-G[00m:[01;34m~/113cse/lab6[00m$ gcc -g -Wall sort_easy.c./a.out[K
2	3	4	4
]0;joey@joey-P7xxDM-G: ~/113cse/lab6[01;32mjoey@joey-P7xxDM-G[00m:[01;34m~/113cse/lab6[00m$ exit
exit

Script done on Fri 21 Oct 2016 10:48:47 AM MDT
