Script started on Wed 26 Oct 2016 07:07:57 PM MDT
]0;joey@joey-P7xxDM-G: ~/113cse/lab7[01;32mjoey@joey-P7xxDM-G[00m:[01;34m~/113cse/lab7[00m$ valgringd [K[Kd[K[Kd.[K ./dynamic 
==3667== Memcheck, a memory error detector
==3667== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==3667== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==3667== Command: ./dynamic
==3667== 
u = "c run, c run unix, run unix run"
u = "c run, c run unix, run unix run, go c, go!"
==3667== 
==3667== HEAP SUMMARY:
==3667==     in use at exit: 0 bytes in 0 blocks
==3667==   total heap usage: 2 allocs, 2 frees, 1,067 bytes allocated
==3667== 
==3667== All heap blocks were freed -- no leaks are possible
==3667== 
==3667== For counts of detected and suppressed errors, rerun with: -v
==3667== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
]0;joey@joey-P7xxDM-G: ~/113cse/lab7[01;32mjoey@joey-P7xxDM-G[00m:[01;34m~/113cse/lab7[00m$ exit
exit

Script done on Wed 26 Oct 2016 07:08:16 PM MDT
