Script started on Wed 26 Oct 2016 07:08:40 PM MDT
]0;joey@joey-P7xxDM-G: ~/113cse/lab7[01;32mjoey@joey-P7xxDM-G[00m:[01;34m~/113cse/lab7[00m$ valgrind ./fun[K[K[Kdynamic 
==3703== Memcheck, a memory error detector
==3703== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==3703== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==3703== Command: ./dynamic
==3703== 
u = "c run, c run unix, run unix run"
u = "c run, c run unix, run unix run, go c, go!"
==3703== 
==3703== HEAP SUMMARY:
==3703==     in use at exit: 43 bytes in 1 blocks
==3703==   total heap usage: 2 allocs, 1 frees, 1,067 bytes allocated
==3703== 
==3703== LEAK SUMMARY:
==3703==    definitely lost: 43 bytes in 1 blocks
==3703==    indirectly lost: 0 bytes in 0 blocks
==3703==      possibly lost: 0 bytes in 0 blocks
==3703==    still reachable: 0 bytes in 0 blocks
==3703==         suppressed: 0 bytes in 0 blocks
==3703== Rerun with --leak-check=full to see details of leaked memory
==3703== 
==3703== For counts of detected and suppressed errors, rerun with: -v
==3703== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
]0;joey@joey-P7xxDM-G: ~/113cse/lab7[01;32mjoey@joey-P7xxDM-G[00m:[01;34m~/113cse/lab7[00m$ .[Kvalgrind --leak-chek[Kck=full ./dynamic 
==3705== Memcheck, a memory error detector
==3705== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==3705== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==3705== Command: ./dynamic
==3705== 
u = "c run, c run unix, run unix run"
u = "c run, c run unix, run unix run, go c, go!"
==3705== 
==3705== HEAP SUMMARY:
==3705==     in use at exit: 43 bytes in 1 blocks
==3705==   total heap usage: 2 allocs, 1 frees, 1,067 bytes allocated
==3705== 
==3705== 43 bytes in 1 blocks are definitely lost in loss record 1 of 1
==3705==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3705==    by 0x40063F: main (dynamic.c:19)
==3705== 
==3705== LEAK SUMMARY:
==3705==    definitely lost: 43 bytes in 1 blocks
==3705==    indirectly lost: 0 bytes in 0 blocks
==3705==      possibly lost: 0 bytes in 0 blocks
==3705==    still reachable: 0 bytes in 0 blocks
==3705==         suppressed: 0 bytes in 0 blocks
==3705== 
==3705== For counts of detected and suppressed errors, rerun with: -v
==3705== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
]0;joey@joey-P7xxDM-G: ~/113cse/lab7[01;32mjoey@joey-P7xxDM-G[00m:[01;34m~/113cse/lab7[00m$ exit
exit

Script done on Wed 26 Oct 2016 07:09:20 PM MDT
